# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Angel0703over"
repo_name: "llm-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/llm-arxiv-daily.json'
json_gitpage_path: './docs/llm-arxiv-daily-web.json'
json_wechat_path: './docs/llm-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index_llm.md'
md_wechat_path: './docs/wechat_llm.md'

# keywords to search
keywords:
    "LLM":
        filters: ["LLM", "RAG", "Agent", "Inference", "LoRA", "Prompt"]

